//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WebFresher042023.Demo.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WebFresher042023.Demo.Core.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài sản &lt;strong&gt;{0}&lt;/strong&gt; nằm trong chứng từ có thời gian điều chuyển lớn hơn!.
        /// </summary>
        public static string CheckTransferAsset {
            get {
                return ResourceManager.GetString("CheckTransferAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua phải nhỏ hơn hoặc bằng ngày bắt đầu theo dõi.
        /// </summary>
        public static string DateError {
            get {
                return ResourceManager.GetString("DateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bộ phận sử dụng không được vượt quá 20 kí tự.
        /// </summary>
        public static string DepartmentCodeLength {
            get {
                return ResourceManager.GetString("DepartmentCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bộ phận sử dụng không được trống.
        /// </summary>
        public static string DepartmentCodeRequired {
            get {
                return ResourceManager.GetString("DepartmentCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID phòng ban.
        /// </summary>
        public static string DepartmentId {
            get {
                return ResourceManager.GetString("DepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID mã bộ phận sử dụng không vượt quá 36 ký tự.
        /// </summary>
        public static string DepartmentIdLength {
            get {
                return ResourceManager.GetString("DepartmentIdLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID mã bộ phận sử dụng không được trống.
        /// </summary>
        public static string DepartmentIdRequired {
            get {
                return ResourceManager.GetString("DepartmentIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng ban.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bộ phận sử dụng không được vượt quá 255 kí tự.
        /// </summary>
        public static string DepartmentNameLength {
            get {
                return ResourceManager.GetString("DepartmentNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bộ phận sử dụng không được trống.
        /// </summary>
        public static string DepartmentNameRequired {
            get {
                return ResourceManager.GetString("DepartmentNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng ban chuyển đi.
        /// </summary>
        public static string DepartmentTransferName {
            get {
                return ResourceManager.GetString("DepartmentTransferName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận chuyển đi phải khác bộ phận hiện tại.
        /// </summary>
        public static string DiffirentDepartment {
            get {
                return ResourceManager.GetString("DiffirentDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản đã tồn tại.
        /// </summary>
        public static string DuplicateDepartmentCode {
            get {
                return ResourceManager.GetString("DuplicateDepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày điều chuyển phải lớn hơn hoặc bằng ngày chứng từ.
        /// </summary>
        public static string ErrorDateInTransferAsset {
            get {
                return ResourceManager.GetString("ErrorDateInTransferAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa chứng từ &lt;strong&gt;{0}&lt;/strong&gt; do tài sản &lt;strong&gt;{1}&lt;/strong&gt; đã phát sinh chứng từ mới hơn!.
        /// </summary>
        public static string ErrorMesageDeleteTransferAsset {
            get {
                return ResourceManager.GetString("ErrorMesageDeleteTransferAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi server. Vui lòng liên hệ bộ phận hỗ trợ!.
        /// </summary>
        public static string ErrorServer {
            get {
                return ResourceManager.GetString("ErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chứng từ điều chuyển đã tồn tại!.
        /// </summary>
        public static string ExistTransferAssetCode {
            get {
                return ResourceManager.GetString("ExistTransferAssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được để trống !.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày theo dõi không được trống.
        /// </summary>
        public static string FollowDateRequired {
            get {
                return ResourceManager.GetString("FollowDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Chứng từ điều chuyển &lt;strong&gt;{0}&lt;/strong&gt; &lt;strong&gt;({1})&lt;/strong&gt;.
        /// </summary>
        public static string InfoTransferAsset {
            get {
                return ResourceManager.GetString("InfoTransferAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa do tài sản &lt;strong&gt;{0}&lt;/strong&gt; đã phát sinh chứng từ !.
        /// </summary>
        public static string NotDeleteProperty {
            get {
                return ResourceManager.GetString("NotDeleteProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tài sản điều chuyển tồn tại tài sản điều chuyển không có trong hệ thống !.
        /// </summary>
        public static string NotExistTransferAssetDetail {
            get {
                return ResourceManager.GetString("NotExistTransferAssetDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tài nguyên với mã Id.
        /// </summary>
        public static string NotFoundId {
            get {
                return ResourceManager.GetString("NotFoundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thao tác do tài sản &lt;strong&gt;{0}&lt;/strong&gt; nằm trong chứng có thời gian điều chuyển mới hơn !.
        /// </summary>
        public static string NotUpdateOrDelete {
            get {
                return ResourceManager.GetString("NotUpdateOrDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số năm sử dụng không được trống.
        /// </summary>
        public static string NumberYearUseRequired {
            get {
                return ResourceManager.GetString("NumberYearUseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên giá.
        /// </summary>
        public static string OriginalPrice {
            get {
                return ResourceManager.GetString("OriginalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị nguyên giá nằm trong khoảng 0 - 999999999999999999.
        /// </summary>
        public static string OriginalPriceRange {
            get {
                return ResourceManager.GetString("OriginalPriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên giá không được trống.
        /// </summary>
        public static string OriginalPriceRequired {
            get {
                return ResourceManager.GetString("OriginalPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        public static string Positon {
            get {
                return ResourceManager.GetString("Positon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị hao mòn phải nhỏ hơn hoặc bằng nguyên giá.
        /// </summary>
        public static string PriceError {
            get {
                return ResourceManager.GetString("PriceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản không được vượt quá 20 kí tự.
        /// </summary>
        public static string PropertyCodeLength {
            get {
                return ResourceManager.GetString("PropertyCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản không được trống.
        /// </summary>
        public static string PropertyCodeRequired {
            get {
                return ResourceManager.GetString("PropertyCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID tài sản.
        /// </summary>
        public static string PropertyId {
            get {
                return ResourceManager.GetString("PropertyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID tài sản không được vượt quá 36 kí tự.
        /// </summary>
        public static string PropertyIdLength {
            get {
                return ResourceManager.GetString("PropertyIdLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID tài sản không được để trống.
        /// </summary>
        public static string PropertyIdRequired {
            get {
                return ResourceManager.GetString("PropertyIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài sản không được vượt quá 255 kí tự.
        /// </summary>
        public static string PropertyNameLength {
            get {
                return ResourceManager.GetString("PropertyNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài sản không được trống.
        /// </summary>
        public static string PropertyNameRequired {
            get {
                return ResourceManager.GetString("PropertyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại tài sản không được vượt quá 20 kí tự.
        /// </summary>
        public static string PropertyTypeCodeLength {
            get {
                return ResourceManager.GetString("PropertyTypeCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại tài sản không được trống.
        /// </summary>
        public static string PropertyTypeCodeRequired {
            get {
                return ResourceManager.GetString("PropertyTypeCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID loại tài sản không được vượt quá 36 kí tự.
        /// </summary>
        public static string PropertyTypeIdLength {
            get {
                return ResourceManager.GetString("PropertyTypeIdLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID loại tài sản không được trống.
        /// </summary>
        public static string PropertyTypeIdRequired {
            get {
                return ResourceManager.GetString("PropertyTypeIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên loại tài sản không được vượt quá 255 kí tự.
        /// </summary>
        public static string PropertyTypeNameLength {
            get {
                return ResourceManager.GetString("PropertyTypeNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên loại tài sản không được trống.
        /// </summary>
        public static string PropertyTypeNameRequired {
            get {
                return ResourceManager.GetString("PropertyTypeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua không được trống.
        /// </summary>
        public static string PurchaseDateRequired {
            get {
                return ResourceManager.GetString("PurchaseDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị số lượng nằm trong khoảng 0 - 999999999999999999.
        /// </summary>
        public static string QuantityRange {
            get {
                return ResourceManager.GetString("QuantityRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng không được trống.
        /// </summary>
        public static string QuantityRequired {
            get {
                return ResourceManager.GetString("QuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải nằm trong khoảng từ {1} - {2}!.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID người nhận.
        /// </summary>
        public static string ReceiverId {
            get {
                return ResourceManager.GetString("ReceiverId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại diện.
        /// </summary>
        public static string Represent {
            get {
                return ResourceManager.GetString("Represent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày chứng từ.
        /// </summary>
        public static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chứng từ.
        /// </summary>
        public static string TransferAssetCode {
            get {
                return ResourceManager.GetString("TransferAssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID tài sản điều chuyển.
        /// </summary>
        public static string TransferAssetDetailId {
            get {
                return ResourceManager.GetString("TransferAssetDetailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tài sản điều chuyển.
        /// </summary>
        public static string TransferAssetDetailList {
            get {
                return ResourceManager.GetString("TransferAssetDetailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID chứng từ.
        /// </summary>
        public static string TransferAssetId {
            get {
                return ResourceManager.GetString("TransferAssetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày điều chuyển.
        /// </summary>
        public static string TransferDate {
            get {
                return ResourceManager.GetString("TransferDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật ngày điều chuyển không thành công do tài sản &lt;strong&gt;{0}&lt;/strong&gt; nằm trong chứng từ khác!.
        /// </summary>
        public static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ lệ hao mòn phải bằng 1/Số năm sử dụng.
        /// </summary>
        public static string WearRateError {
            get {
                return ResourceManager.GetString("WearRateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ lệ hao mòn không được trống.
        /// </summary>
        public static string WearRateRequired {
            get {
                return ResourceManager.GetString("WearRateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị hao mòn năm không được trống.
        /// </summary>
        public static string WearRateValueRequired {
            get {
                return ResourceManager.GetString("WearRateValueRequired", resourceCulture);
            }
        }
    }
}
